DECLARE
BEGIN
  UPDATE CIS2.RENIM
  SET DENUMIRE = TRIM(TRANSLATE(DENUMIRE, CHR(10) || CHR(11) || CHR(13), '   ')),
      IDNO = TRIM(TRANSLATE(IDNO, CHR(10) || CHR(11) || CHR(13), '   '))
  WHERE (INSTR(DENUMIRE, CHR(13)) > 0
    OR INSTR(DENUMIRE, CHR(10)) > 0
    OR INSTR(DENUMIRE, CHR(11)) > 0)
    OR (INSTR(IDNO, CHR(13)) > 0
    OR INSTR(IDNO, CHR(10)) > 0
    OR INSTR(IDNO, CHR(11)) > 0)
    AND CUIIO = 10065422;
END;
/