-- Find and remove whitespace characters from the FORMULA column

-- Update the FORMULA column
--UPDATE USER_EREPORTING.MD_CONTROL
--SET FORMULA = REPLACE(REPLACE(REPLACE(FORMULA, CHR(10), ''), CHR(11), ''), CHR(13), '')
--WHERE INSTR(FORMULA, CHR(10)) > 0 OR INSTR(FORMULA, CHR(11)) > 0 OR INSTR(FORMULA, CHR(13)) > 0
--
--AND CONTROL IN ('07-014');

---- Select the modified data
SELECT CONTROL,
       CONTROL_VERS,
       TRIM(FORMULA) AS FORMULA
FROM USER_EREPORTING.MD_CONTROL
WHERE INSTR(FORMULA, CHR(10)) > 0 OR INSTR(FORMULA, CHR(11)) > 0 OR INSTR(FORMULA, CHR(13)) > 0;
